=== project-thera/thera-mobile-app/docs/data/generated_json_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "_id": "string",
    "_rev": "string",
    "blowConfig": {
      "type": "object",
      "properties": {
        "sampleRate": "integer"
      }
    },
    "cameraResolution": {
      "type": "object",
      "properties": {
        "height": "integer",
        "width": "integer"
      }
    },
    "data": {
      "type": "object",
      "properties": {
        "created_at": "string",
        "discarded_at": "string",
        "email": "string",
        "file": "string",
        "fullname": "string",
        "game_reward_id": "integer",
        "id": "integer",
        "supervisor_id": "integer",
        "updated_at": "string",
        "username": "string"
      }
    },
    "gameReward": {
      "type": "object",
      "properties": {
        "credits": "integer",
        "current_robot": "integer",
        "id": "string",
        "robots": "integer"
      }
    },
    "routineIntents": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "finished_at": "string",
            "routine_id": "string",
            "routine_intent_exercises_attributes": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "exercise_id": "string",
                    "status": "integer"
                  }
                }
              ]
            },
            "started_at": "string"
          }
        }
      ]
    },
    "routines": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "created_at": "string",
            "daily_limit": "integer",
            "discarded": "boolean",
            "id": "string",
            "name": "string",
            "patient_id": "string",
            "routine_exercises": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "created_at": "string",
                    "exercise": {
                      "type": "object",
                      "properties": {
                        "created_at": "string",
                        "description": "string",
                        "exercise_type": "string",
                        "id": "string",
                        "name": "string",
                        "steps": "string",
                        "updated_at": "string"
                      }
                    },
                    "exercise_id": "integer",
                    "id": "string",
                    "repetitions": "integer",
                    "routine_id": "integer",
                    "updated_at": "string"
                  }
                }
              ]
            },
            "supervisor_id": "string",
            "updated_at": "string"
          }
        }
      ]
    },
    "token": "string"
  }
}

=== project-thera/thera-mobile-app/docs/data/pouchdb_example2.json
{
    "_id": "current",
    "_rev": "18-8e2c8c0147a54f13963febe966de0c93",
    "blowConfig": {
        "sampleRate": 12
    },
    "cameraResolution": {
        "height": 1080,
        "width": 1920
    },
    "data": {
        "created_at": "2022-04-28T19:54:54.607-03:00",
        "discarded_at": null,
        "email": "paciente@thera.com.ar",
        "file": null,
        "fullname": "María Elisa Galli",
        "game_reward_id": 84,
        "id": 84,
        "supervisor_id": 63,
        "updated_at": "2022-05-04T20:56:13.242-03:00",
        "username": "paciente"
    },
    "gameReward": {
        "credits": 20,
        "current_robot": 0,
        "id": "84",
        "robots": 0
    },
    "routineIntents": [{
        "finished_at": "2022-05-05T00:12:04.598Z",
        "routine_id": "228",
        "routine_intent_exercises_attributes": [{
            "exercise_id": "27",
            "status": 0
        }],
        "started_at": "2022-05-05T00:12:02.157Z"
    }],
    "routines": [{
        "created_at": "2022-04-28T19:56:09.739-03:00",
        "daily_limit": 3,
        "discarded": false,
        "id": "223",
        "name": "número #84 #1",
        "patient_id": "84",
        "routine_exercises": [{
                "created_at": "2022-04-28T19:56:09.741-03:00",
                "exercise": {
                    "created_at": "2022-04-28T19:54:54.791-03:00",
                    "description": "Acerque el celular a su cara y sople durante 5 segundos.",
                    "exercise_type": "blow",
                    "id": "29",
                    "name": "Soplido 5 segundos",
                    "steps": "[{\"goal\":\"soplar\",\"time\":5000},{\"goal\":\"sin_soplar\",\"time\":5000}]",
                    "updated_at": "2022-04-28T19:54:54.791-03:00"
                },
                "exercise_id": 29,
                "id": "1691",
                "repetitions": 1,
                "routine_id": 223,
                "updated_at": "2022-04-28T19:56:09.741-03:00"
            },
            {
                "created_at": "2022-04-28T19:56:09.749-03:00",
                "exercise": {
                    "created_at": "2022-04-28T19:54:54.874-03:00",
                    "description": "Presione el bóton y pronuncie \"Elefante\".",
                    "exercise_type": "speech",
                    "id": "35",
                    "name": "Elefante",
                    "steps": "[{\"goal\":\"elefante\",\"image\":\"data:image/png;base64,...\"}]",
                    "updated_at": "2022-04-28T19:54:54.874-03:00"
                },
                "exercise_id": 35,
                "id": "1696",
                "repetitions": 1,
                "routine_id": 223,
                "updated_at": "2022-04-28T19:56:09.749-03:00"
            }, {
                "created_at": "2022-04-28T19:56:09.751-03:00",
                "exercise": {
                    "created_at": "2022-04-28T19:54:54.761-03:00",
                    "description": "Use la cámara del celular y realize lengua en círulo.",
                    "exercise_type": "classification",
                    "id": "25",
                    "name": "Lengua en círulo",
                    "steps": "[{\"goal\":\"lengua_arriba\",\"time\":1000},{\"goal\":\"lengua_derecha\",\"time\":1000},{\"goal\":\"lengua_abajo\",\"time\":1000},{\"goal\":\"lengua_izquierda\",\"time\":1000}]",
                    "updated_at": "2022-04-28T19:54:54.761-03:00"
                },
                "exercise_id": 25,
                "id": "1697",
                "repetitions": 1,
                "routine_id": 223,
                "updated_at": "2022-04-28T19:56:09.751-03:00"
            }
        ],
        "supervisor_id": "63",
        "updated_at": "2022-04-28T19:56:09.739-03:00"
    }],
    "token": "GIloXAufvdshFRFJtfrUBh3MiZNB2yHK/kmrKK+XbUlBf0xMFElOB77izdCGR1NDZPT0iEd6md71QxPtraIcdQ=="
}
